dist: trusty
branches:
  except:
  - master
addons:
  sonarcloud:
    organization: bbpl
    token:
      secure: 8K5nEOG+9yMC/YhtjD18q0WJdyY7rWvbBvy6+ZHkc7JlKY04bGQ62YBDBroGUiOTgMkhPbvIN+qh7l5ImFDsZBXjYn3ImfMol4muyZl14bLPElDOj/2TU2uZluWlJ8Yyv60V9ZPikt63gL6FD8peJur/pB4ylNJHhuaTEVV+Hp+BZzZ7mItPIFpyskiPXb3i9g5z1WoIdHnC7odKgOIqfJjhVRglIjVoWdVNSxTX7Ikt3PmlosDskCQsGV34rrUpTgE+VDYzLFjgpSKFaXPxsatCHb+RM7fYYZDsgEnJOlOfK/Q9FcUXFDjUGKjTvPXJRLV8SeVvMq1WX3JFqN2SAwtXvmtlieLivnWVQwNC3FoA9jNYRqmm1NaA8BnjmaA5Oxz1a+KbWdvw2473WNO1st/Rlqr8aSNTF/gsE30jtsawC8cT56XBdyt+RQOJSEDK+vy4zEVK+SaV4i9dL2TxaY7xYxi9nE1SvnucuqMP3EYo0dMweCyHDaGwC8G/o+kpnOn9U1b/zwAydwcs8Gl3hfv/pAHXvTf2vrNJkhhMKqv0ChqcoJvlId6rVowpbZHMybm+kcUsu8T0L3h0jIHCJCb9N792QygcuqPWQs39Z7bRiFrXIHw1SPcWzfwgkL2fyqoBEycNDN2VhJKNVjGJ15Pf/knzbSs7El9llS0ac78=
jobs:
  include:
  - stage: analysis
    name: Analysis Code
    script:
    - sonar-scanner -X
env:
  global:
    secure: DVdvnptW3VwBrEELnhbu5dApWki0fIHyOZ+CSos3EqSRNopHkfALwVgW/l1DEJOfMH8Ftk4pooriYoZMhwAtEGhTHOxQei4NFBXboEiF+QuV+3ipFko01AJfJxo6GiXHdnWTjAZVHrdEzv7Ih6BK6lke9qfInxop4bLiXCG9jSovtt4pywFTzdWxDTZsszaz0xreF+AG8TCEEnctlnWvXIuBn9yKp0BfMcT3+ACNYIbVlSEqcJQ6ZQALOWlTNPRAuPJotAJ2/trpDjvL1JmHEHuUMpQMMtXz5ORy6w0ePoaBqOXfYcGxPMaI8PlosSUCwoZzu8ecabw+W6W9rld9lZzpuMAMq0pSeiYFTfBgu4odK76iFRDeO0iMoMIekUAi6KVwvbeS5N7UH1hn9z6xmu3/JPVtpN9P7jbUYfO5Tfct5wWDfn7EhHj+7ww4TZklVavbke3U2FsI+t4ExbBeIXFg+T2eK+nzmLKkgIHnGBN1qMpTzxOIl0ss27xVNvAi46qRl1nRH84ditFLIL4afpTVfX55Iy1oW+01RufFpQVWUpKTKhB2z7GYYpQk2YfUTy+LF2j4qOitl1ZnWtIB7EEqWQPacrxa1IyLv8Jkaspa3UbMHfEa5Z+lxxW8kgFvQXZ0WKdudnCN5i6/oD5mhKEXkihsqdVGvn7fIjRrrtY=
