language: csharp
mono: none

dotnet: 3.1.100

install:
  - dotnet restore API/Solution1.sln

jobs:
  include:
    - stage: build
      name: "Build Solution"
      script: 
        - dotnet build --configuration Release API/Solution1.sln

    - stage: test
      name: "Run Tests"
      script: 
        - dotnet test API/Minitwit.Tests/Minitwit.Tests.csproj

    - stage: deliver
      name: Upload artifact
      if: branch = develop
      script:
        - echo "Push image"

notifications:
  email:
    - krza@itu.dk
    - mr.kislun@gmail.com
    - phko@itu.dk
    - alsb@itu.dk
    - arca@itu.dk
