language: csharp
mono: none

dotnet: 3.1.100
services:
  - docker
install:
  - dotnet restore API/Solution1.sln
branches:
  except:
    - master

addons:
  sonarcloud:
    organization: "lazyopsdev"
    token:
      secure: "sifBGDoyDCBLu3Ho8H/3+t4sHKQ2qmvDFIZCi5JxTrNxW5eYwvI+qzRnCdg/zDnkbv1kVf7YVIjfFhO362DOMSRaTols+A66TMI4bUubVs6jzUsSxKvCg8qUaFXbD7qsJzKOx5BpHMPiD6ptUr3FfYSQRmQHUsMj4Cqa6fY1A5bBTYMFlM4PjmzWxWYV2NjC0mJPoOp0VnbEC1qn2dMmmTl0df4OJ3zk90rSAAouql3tzVLOPS4JQ/1aspfT0Pbb9of4ORy+4Syv7grp+8KJI0GMonikcyXtbFAGoZdZ011mQ2wArQYjtw1ALCq9cN//6C00GaAnoR09iHUacLomFpIB/cNTbCdiq4ENzxW1ICKnVa8HEQwOfuNULFGrajHS5IbIuHrAJReQj1HFbmVjMINuY6a9PXKvinUyw3RT5wTwRgFoMG7VoBdmWxeTm4pCa2dDt36D/fo/e9O3eOWbohZaVGnYe/DdgdrWZm1hwFgBD/GTjbzJ3sgLLU+Qhxh7kQ1aD6fLlORKH0ShlvDNk5LjLE/nr/KixwCy/qru45yrV6Nb7FL17B+7xrAxUOKNgB0XUSxQ6SizIfOb7wFLNtZF/GT0SdlYYpYmqNnUmscBAUcoL8cEzh9nI0HsPsGmXXgOykXHJGwn1Yx3aA7hJOKSlB2Cz3Ar7+DB0eHHNK4=" # encrypted value of your token

jobs:
  include:
    # Build and run tests
    - stage: analysis
      name: "Analysis Code"
      script:
        - sonar-scanner

    - stage: build
      name: "Build Solution"
      script: 
        - dotnet build --configuration Release API/Solution1.sln
        - echo "Build"

    - stage: test
      name: "Run Tests"
      script: 
        - dotnet test API/Minitwit.Tests/Minitwit.Tests.csproj
        - echo "Test"

    # Build docker image and push to dockerhub:
    # - stage: deliver
    #   if: tag IS present
    #   name: Upload docker image
    #   env:
    #     - ORG_NAME=lazyopsdev
    #     - IMAGE_NAME=api
    #     - DEFAULT_DOCKER_TAG=latest
    #   script:
    #     - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #     - cd API && docker build -t $IMAGE_NAME .
    #     - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
    #     - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"
    #     - docker push "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
    #     - docker push "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"

    # GitHub auto merge to master:
    - stage: auto-merge
      if: tag IS present
      name: Merge to master
      env:
        - GITHUB_USER_EMAIL="lazyopsdev@gmail.com"
        - GITHUB_USER_NAME="lazyopsdev-ci"
        - GITHUB_REPO_URI="LazyOpsDev/Minitwit.Backend"
      script:
        - git config --global user.email "$GITHUB_USER_EMAIL"
        - git config --global user.name "$GITHUB_USER_NAME"
        - git config --add remote.origin.fetch +refs/heads/*:refs/remotes/origin/* || exit
        - git fetch --all || exit
        - git checkout master || exit
        - git merge --no-ff "$TRAVIS_COMMIT" || exit
        - git remote add travis-origin https://${GITHUB_USER_NAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO_URI}.git > /dev/null 2>&1
        - git push --quiet --set-upstream travis-origin master

notifications:
  email:
    - krza@itu.dk
    - phko@itu.dk
    - alsb@itu.dk
    - arca@itu.dk
