language: csharp
mono: none
env:
  - ORG_NAME=lazyopsdev
  - IMAGE_NAME=api
  - DEFAULT_DOCKER_TAG=latest

dotnet: 3.1.100
services:
  - docker
install:
  - dotnet restore API/Solution1.sln

jobs:
  include:
    - stage: build
      name: "Build Solution"
      script: 
        #- dotnet build --configuration Release API/Solution1.sln
        - echo "Build"

    - stage: test
      name: "Run Tests"
      script: 
        #- dotnet test API/Minitwit.Tests/Minitwit.Tests.csproj
        - echo "Test"

    - stage: deliver
      if: tag IS present
      name: Upload docker image
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - cd API && docker build -t $IMAGE_NAME .
        - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
        - docker tag $IMAGE_NAME "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"
        - docker push "$ORG_NAME/$IMAGE_NAME:$TRAVIS_TAG"
        - docker push "$ORG_NAME/$IMAGE_NAME:$DEFAULT_DOCKER_TAG"
        # - git fetch origin master && git checkout master || exit
        # - git merge develop || exit
        # - git push origin master

notifications:
  email:
    - krza@itu.dk
    - mr.kislun@gmail.com
    - phko@itu.dk
    - alsb@itu.dk
    - arca@itu.dk
