language: csharp
mono: none

dotnet: 3.1.100
install:
  - dotnet restore API/Solution1.sln
script:
  - dotnet build --configuration Release API/Solution1.sln
  - dotnet test API/Minitwit.Tests/Minitwit.Tests.csproj

notifications:
  email:
    - krza@itu.dk
    - mr.kislun@gmail.com
    - phko@itu.dk
    - alsb@itu.dk
    - arca@itu.dk
