 version: 2.1
 jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: dotnet restore API/Solution1.sln
      - run: dotnet build --configuration Release API/Solution1.sln
  test:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1
    steps:
      - checkout
      - run: dotnet test API/Minitwit.Tests/Minitwit.Tests.csproj
